create table if not exists public.tournaments (
  id integer primary key,
  name text not null,
  type text not null,
  entry_value integer not null,
  reentry_value integer not null,
  addon_value integer not null,
  payout_places integer not null,
  level_minutes integer not null,
  small_blind integer not null,
  big_blind integer not null,
  ante integer not null,
  timer_started_at bigint,
  timer_paused_seconds integer not null,
  updated_at bigint not null
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  nickname text not null default '',
  phone text not null default '',
  email text not null default '',
  document text not null default '',
  notes text not null default '',
  status text not null,
  entries integer not null default 0,
  reentries integer not null default 0,
  addons integer not null default 0,
  chips integer not null default 0,
  table_no text not null default '',
  eliminated_at bigint,
  created_at bigint not null
);

create index if not exists idx_players_status on public.players(status);

create table if not exists public.financial_transactions (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  kind text not null check (kind in ('entry', 'reentry', 'addon', 'payment')),
  quantity integer not null default 1,
  unit_amount integer not null,
  total_amount integer not null,
  payment_method text not null default '',
  note text not null default '',
  created_at bigint not null,
  voided_at bigint
);

create index if not exists idx_financial_transactions_player_id on public.financial_transactions(player_id);
create index if not exists idx_financial_transactions_kind on public.financial_transactions(kind);

alter table public.tournaments enable row level security;
alter table public.players enable row level security;
alter table public.financial_transactions enable row level security;
revoke all on public.tournaments, public.players, public.financial_transactions from anon, authenticated;

insert into public.tournaments (id, name, type, entry_value, reentry_value, addon_value, payout_places, level_minutes, small_blind, big_blind, ante, timer_started_at, timer_paused_seconds, updated_at)
values (1, 'Torneio Principal', 'Freezeout', 10000, 10000, 5000, 3, 20, 100, 200, 200, null, 1200, extract(epoch from now())::bigint * 1000)
on conflict (id) do nothing;
